### ISSUE TITLE
Leave intro to Arrays and Hashes out of this lesson?

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/ruby-vs-js#2]
Wondering if it is logical to keep the short intro to Ruby arrays and hashes here since they'll be covered much more in depth in the two consecutively following lessons...

Thoughts? @gaand @jrhorn424

**Comment by gaand** [comment]
@laurenfazah I think the brief introduction makes sense.  Tell them, then tell them again (and again :-).).

**Comment by laurenfazah** [comment]
@gaand sounds good!
