### ISSUE TITLE
Favor `1.upto(max) do |n|` over  `for i in `1..max` do

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-vs-js#5]
Avoid for loops as not rubyish.

**Comment by laurenfazah** [comment]
Big whoops on my part.

**Comment by gaand** [comment]
Not at all.

**Comment by payne-chris-r** [comment]
@gaand please close if you find the solution in ed51c00 adequate.

**Comment by gaand** [comment]
@payne-chris-r 

Only do this once:

``` ruby
for i in 1.upto(max) do
```

After that, tell developers to avoid as non-idiomatic and instead use:

``` ruby
1.upto(max) do |i|
```

**Comment by payne-chris-r** [comment]
As we talked about in the hall, I understand this now. I didn't originally understand that you wanted the `for` removed completely after we showed it to them once. It makes sense--it's very un-ruby. I just thought we wanted to be analogous to js for awhile/not freak them out so much.

**Comment by laurenfazah** [comment]
All set here to close @gaand
